services:
  test_app:
    build:
      context: .
    env_file:
      - .env.test
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    depends_on:
      - test_database
    
  test_database:
    image: postgres:18-alpine
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.test

volumes:
  test_postgres_data:
